### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by atulkum** [mrniko/netty-socketio-demo#12]
The client side is giving this error:
XMLHttpRequest cannot load http://127.0.0.1:9092/socket.io/1/?t=1408262517434. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

The server is giving this error:
[nioEventLoopGroup-3-4] WARN com.corundumstudio.socketio.handler.WrongUrlHandler - Blocked wrong socket.io-context request! url: /socket.io/1/, params: {t=[1408262517434]}, ip: /127.0.0.1:51783

Tried setting config.setOrigin("http://127.0.0.1"); ("_:_" etc.)but does not work.

**Comment by noahxinhao** [comment]
me too :(

**Comment by mrniko** [comment]
@noahxinhao could you provide more details?

**Comment by newpanjing** [comment]
me too。。。
