### ISSUE TITLE
how to use same port used by tomcat, as we can do in case of node.js + express

### ISSUE THREAD

**Issue by mrudangit** [mrniko/netty-socketio-demo#24]
in node.js and express socket.io can use same port used by http.

how can we achieve this here in java

**Comment by mrniko** [comment]
use SO_REUSEADDR socket param

**Comment by mrudangit** [comment]
so i let first Tomcat initialize on 8080 then i start netty-socketio server using 
SocketConfig socketconfig = new SocketConfig();
socketconfig.setReuseAddress(true);
config.setSocketConfig(socketconfig);

still get 
Caused by: java.net.BindException: Address already in use: bind

**Comment by mrudangit** [comment]
never mind . I get it now this is netty based so it will create its own serverloop
